"""Synthetic registry generator. Deterministic for a given seed. Nothing here is real.

The registry exists so the Definition Lab and the maturity views can be exercised on a
population whose properties are known. It never describes a real entity.
"""

from __future__ import annotations

import math
import random

from .schemas import Registry, RegistryMeta, ServiceItem, SyntheticEntity

GENERATOR_VERSION = "1.0"
SEED = 20260423

DISCLAIMER = (
    "SYNTHETIC DATA. Every entity, service and figure in this registry was generated by a seeded "
    "script. None of it describes a real government entity, service or system, and it must not be "
    "read as a statement about any of them."
)

SECTORS = [
    "Health",
    "Education",
    "Transport",
    "Economy",
    "Justice",
    "Municipal",
    "Social",
    "Finance",
]

_SERVICE_NAMES = [
    "licence renewal",
    "permit application",
    "certificate issuance",
    "benefit enquiry",
    "appointment booking",
    "fee payment",
    "complaint handling",
    "registration update",
    "eligibility check",
    "document request",
]
_OPERATION_NAMES = [
    "procurement review",
    "case triage",
    "records classification",
    "budget reconciliation",
    "workforce planning",
    "policy drafting support",
    "inspection scheduling",
    "audit sampling",
]


def _maturity(rng: random.Random, adv: float, operation: bool) -> int:
    x = rng.gauss(adv * 4.0 - (0.4 if operation else 0.0), 0.9)
    return max(0, min(4, round(x)))


def generate(seed: int = SEED, n_entities: int = 16, items_per_entity: int = 38) -> Registry:
    rng = random.Random(seed)
    entities: list[SyntheticEntity] = []
    for i in range(n_entities):
        sector = SECTORS[i % len(SECTORS)]
        entities.append(
            SyntheticEntity(
                id=f"SE{i + 1:02d}",
                name=f"Synthetic {sector} Authority {chr(65 + i // len(SECTORS))}",
                sector=sector,
                advancement=round(min(1.0, max(0.05, rng.betavariate(2.2, 2.0))), 3),
            )
        )
    items: list[ServiceItem] = []
    for e in entities:
        k = max(10, int(rng.gauss(items_per_entity, 6)))
        for j in range(k):
            operation = rng.random() < 0.28
            audience = (
                "internal" if operation else rng.choices(["citizen", "business"], weights=[0.65, 0.35])[0]
            )
            m = _maturity(rng, e.advancement, operation)
            # Guardrails are more often present on high-maturity items, but not reliably.
            p = 0.45 + 0.1 * m
            tx = 0 if operation and rng.random() < 0.5 else int(math.exp(rng.gauss(8.5, 1.8)))
            name = rng.choice(_OPERATION_NAMES if operation else _SERVICE_NAMES)
            items.append(
                ServiceItem(
                    id=f"{e.id}-{j + 1:03d}",
                    entity_id=e.id,
                    sector=e.sector,
                    kind="operation" if operation else "service",
                    audience=audience,
                    name=name,
                    annual_transactions=tx,
                    maturity=m,
                    oversight=rng.random() < min(0.95, p + 0.1),
                    audit_trail=rng.random() < min(0.95, p + 0.15),
                    uae_residency=rng.random() < min(0.97, p + 0.3),
                    fallback=rng.random() < min(0.95, p),
                )
            )
    return Registry(
        meta=RegistryMeta(seed=seed, generator_version=GENERATOR_VERSION, disclaimer=DISCLAIMER),
        entities=entities,
        items=items,
    )
